# BUILDING THE APPLICATION
FROM node:18-alpine as app-build

WORKDIR /app

COPY /app/package.json .
COPY /app/package-lock.json .

RUN npm ci

COPY /app .

RUN npm run build

# DEPLOYING THE BUILD
FROM nginx:1.23.1-alpine

COPY --from=app-build /app/build /usr/share/nginx/html

COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
