- name: Install Docker
  hosts: deploy
  become: yes
  tasks:
  - name: Is docker installed
    shell: command -v docker >/dev/null 2>&1
    register: is_docker
    ignore_errors: yes

  - debug: msg="Has docker - {{ is_docker.rc == 0 }}"

  - name: Installing docker
    shell: apt install docker.io -y
    when: is_docker.rc != 0

  - name: Is docker-compose installed
    shell: command -v docker-compose >/dev/null 2>&1
    register: is_docker_compose
    ignore_errors: yes

  - debug: msg="Has docker-compose - {{ is_docker_compose.rc == 0 }}"

  - name: Installing docker-compose
    apt:
      name: docker-compose
      state: present
    when: is_docker.rc != 0
