- name: Build the project
  hosts: build
  become: yes
  tasks:
  - name: Install git package
    apt:
      name: git
      state: present

  - name: Clone project from GitHub
    git:
      repo: https://github.com/tyomka896/devops
      dest: /tmp/project
      version: 07-docker-compose

  - name: Build project with docker compose
    shell:
      cmd: "docker-compose up -d --build"
      chdir: /tmp/project

  - name: Copy build to local temporary folder
    synchronize:
      src: /tmp/project/app/build/
      dest: ./_build
      mode: pull

  - name: Remove temporary project folder
    file:
      path: /tmp/project
      state: absent

- name: Deploy the project
  hosts: deploy
  become: yes
  tasks:
  - name: Install nginx package
    apt:
      name: nginx
      state: present

  - name: Is nginx started
    service:
      name: nginx
      state: started

  - name: Copy build to the server
    synchronize:
      src: ./_build/
      dest: /var/www/html

- name: Local machine
  hosts: localhost
  connection: local
  tasks:
  - name: Clear temporary build folder (optional)
    file:
      path: ./_build/
      state: absent
    when: clear is defined and clear == 'yes'
